const todoList = [
    {
        name: 'todo1',
        title: 'Buy groceries',
        descr: 'Milk',
        date: '12.01.2023',
        isDone: false,
    },
    {
        name: 'todo4',
        title: 'Write report',
        descr: 'Prepare document for manager.',
        date: '20.01.2023',
        isDone: true,
    },
    {
        name: 'todo2',
        title: 'Call doctor',
        descr: 'Make an appointment with the therapist.',
        date: '15.01.2023',
        isDone: true,
    },
    {
        name: 'todo3',
        title: 'Do cleaning',
        descr: 'Vacuum and mop the floors. Also dust the shelves, clean the mirrors and wash the bathroom sink properly.',
        date: '17.01.2023',
        isDone: false,
    },
    {
        name: 'todo4',
        title: 'Write report',
        descr: 'Prepare document for manager.',
        date: '20.01.2023',
        isDone: true,
    },
    {
        name: 'todo5',
        title: 'Buy gift',
        descr: 'Find a present for friend’s birthday. Think about something personal, maybe a book, board game or tech gadget. Wrap it nicely and buy a birthday card too.',
        date: '25.01.2023',
        isDone: false,
    },
    {
        name: 'todo6',
        title: 'Go jogging',
        descr: '5 km run in the park.',
        date: '26.01.2023',
        isDone: true,
    },
    {
        name: 'todo7',
        title: 'Watch movie',
        descr: 'Pick a new film for the evening.',
        date: '28.01.2023',
        isDone: false,
    },
    {
        name: 'todo8',
        title: 'Refuel car',
        descr: 'Fill the gas tank full. Also check tire pressure and windshield washer fluid level just in case before the weekend trip.',
        date: '30.01.2023',
        isDone: true,
    },
    {
        name: 'todo9',
        title: 'Do homework',
        descr: 'Solve math problems.',
        date: '02.02.2023',
        isDone: false,
    },
    {
        name: 'todo10',
        title: 'Read book',
        descr: 'Finish the next chapter.',
        date: '05.02.2023',
        isDone: true,
    },
    {
        name: 'todo11',
        title: 'Go to gym',
        descr: 'Workout for chest and back. Don’t forget warm-up, stretching, and write down progress in the notebook. Drink enough water during the training.',
        date: '07.02.2023',
        isDone: false,
    },
    {
        name: 'todo12',
        title: 'Buy clothes',
        descr: 'Get a new jacket.',
        date: '10.02.2023',
        isDone: true,
    },
    {
        name: 'todo13',
        title: 'Visit grandma',
        descr: 'Bring cake and tea.',
        date: '12.02.2023',
        isDone: false,
    },
    {
        name: 'todo14',
        title: 'Backup files',
        descr: 'Upload photos and docs to cloud. Make sure to also check old folders on the external drive, reorganize files into proper categories, and confirm backup finished successfully.',
        date: '15.02.2023',
        isDone: true,
    },
    {
        name: 'todo15',
        title: 'Take out trash',
        descr: 'Throw garbage in the evening.',
        date: '16.02.2023',
        isDone: false,
    },
];


export default todoList